import json
import string
import random
import firebase_admin
from PyQt5.QtCore import Qt
from firebase_admin import credentials
from firebase_admin import db
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QMessageBox
import requests
import re
import pkg_resources
import os

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

class Ui_MainWindow(object):
    AdvPage = False
    currUser = None
    firebase_config = {
        "apiKey": "AIzaSyDB-6H5PEWpLOBqa-3eS7MXeu2s8HPE_z0",
        "authDomain": "randompasswordgenerator-1f500.firebaseapp.com",
        "databaseURL": "https://randompasswordgenerator-1f500-default-rtdb.asia-southeast1.firebasedatabase.app",
        "projectId": "randompasswordgenerator-1f500",
        "storageBucket": "randompasswordgenerator-1f500.appspot.com",
        "messagingSenderId": "161773452179",
        "appId": "1:161773452179:web:8539545fa2d82e23b4c666",
        "measurementId": "G-TH9SEDG6C6"
    }
    current_directory = os.path.dirname(os.path.abspath(__file__))
    json_file_name = "RPG_secreatKey.json"
    json_file_path = os.path.join(current_directory, json_file_name)
    json_data = pkg_resources.resource_string(__name__, json_file_name)
    service_account_info = json.loads(json_data.decode('utf-8'))
    cred = credentials.Certificate(service_account_info)
    firebase_admin.initialize_app(cred, {"databaseURL":firebase_config['databaseURL']})
    root_ref = db.reference()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 923)
        MainWindow.setStyleSheet("background-color: rgb(212, 212, 212);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AppName_label = QtWidgets.QLabel(self.centralwidget)
        self.AppName_label.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.AppName_label.setFont(font)
        self.AppName_label.setStyleSheet("background-color: rgb(0, 170, 255);\n"
                                         "color: rgb(255, 255, 255);")
        self.AppName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.AppName_label.setObjectName("AppName_label")
        self.verticalLayout.addWidget(self.AppName_label)
        self.MenuLayout = QtWidgets.QHBoxLayout()
        self.MenuLayout.setContentsMargins(30, 0, 50, 0)
        self.MenuLayout.setSpacing(15)
        self.MenuLayout.setObjectName("MenuLayout")
        self.SimPass_PBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SimPass_PBtn.setMinimumSize(QtCore.QSize(170, 50))
        self.SimPass_PBtn.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SimPass_PBtn.setFont(font)
        self.SimPass_PBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SimPass_PBtn.setStyleSheet("border-color: rgb(161, 161, 161);")
        self.SimPass_PBtn.setDefault(False)
        self.SimPass_PBtn.setFlat(False)
        self.SimPass_PBtn.setObjectName("SimPass_PBtn")
        self.MenuLayout.addWidget(self.SimPass_PBtn)
        self.AdvPass_PBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AdvPass_PBtn.setMinimumSize(QtCore.QSize(170, 50))
        self.AdvPass_PBtn.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.AdvPass_PBtn.setFont(font)
        self.AdvPass_PBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdvPass_PBtn.setObjectName("AdvPass_PBtn")
        self.MenuLayout.addWidget(self.AdvPass_PBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 70, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.MenuLayout.addItem(spacerItem)
        self.UserNm_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.UserNm_label.setFont(font)
        self.UserNm_label.setText("")
        self.UserNm_label.setObjectName("UserNm_label")
        self.MenuLayout.addWidget(self.UserNm_label)
        self.Login_PBtn = QtWidgets.QPushButton(self.centralwidget)
        self.Login_PBtn.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Login_PBtn.setFont(font)
        self.Login_PBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login_PBtn.setObjectName("Login_PBtn")
        self.MenuLayout.addWidget(self.Login_PBtn)
        self.verticalLayout.addLayout(self.MenuLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.PassGen_Page = QtWidgets.QWidget()
        self.PassGen_Page.setObjectName("PassGen_Page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.PassGen_Page)
        self.horizontalLayout_5.setContentsMargins(-1, 50, -1, -1)
        self.horizontalLayout_5.setSpacing(9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(39)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PassGen_formLayout = QtWidgets.QFormLayout()
        self.PassGen_formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.PassGen_formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.PassGen_formLayout.setContentsMargins(0, -1, -1, -1)
        self.PassGen_formLayout.setHorizontalSpacing(40)
        self.PassGen_formLayout.setVerticalSpacing(20)
        self.PassGen_formLayout.setObjectName("PassGen_formLayout")
        self.PassLen_label = QtWidgets.QLabel(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PassLen_label.setFont(font)
        self.PassLen_label.setObjectName("PassLen_label")
        self.PassGen_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.PassLen_label)
        self.PassLength_SEdit = QtWidgets.QSpinBox(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PassLength_SEdit.setFont(font)
        self.PassLength_SEdit.setMinimum(4)
        self.PassLength_SEdit.setProperty("value", 4)
        self.PassLength_SEdit.setObjectName("PassLength_SEdit")
        self.PassGen_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PassLength_SEdit)
        self.CharSet_label = QtWidgets.QLabel(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CharSet_label.setFont(font)
        self.CharSet_label.setObjectName("CharSet_label")
        self.PassGen_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CharSet_label)
        self.charSet_VLayout = QtWidgets.QVBoxLayout()
        self.charSet_VLayout.setObjectName("charSet_VLayout")
        self.charsetchoices_Hlayout = QtWidgets.QHBoxLayout()
        self.charsetchoices_Hlayout.setObjectName("charsetchoices_Hlayout")
        self.AlphaSet_checkbox = QtWidgets.QCheckBox(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AlphaSet_checkbox.setFont(font)
        self.AlphaSet_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AlphaSet_checkbox.setObjectName("AlphaSet_checkbox")
        self.charsetchoices_Hlayout.addWidget(self.AlphaSet_checkbox)
        self.NumSet_checkbox = QtWidgets.QCheckBox(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NumSet_checkbox.setFont(font)
        self.NumSet_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NumSet_checkbox.setObjectName("NumSet_checkbox")
        self.charsetchoices_Hlayout.addWidget(self.NumSet_checkbox)
        self.SpeCharSet_checkbox = QtWidgets.QCheckBox(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SpeCharSet_checkbox.setFont(font)
        self.SpeCharSet_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SpeCharSet_checkbox.setObjectName("SpeCharSet_checkbox")
        self.charsetchoices_Hlayout.addWidget(self.SpeCharSet_checkbox)
        self.charSet_VLayout.addLayout(self.charsetchoices_Hlayout)
        self.addCharSet_Hlayout = QtWidgets.QHBoxLayout()
        self.addCharSet_Hlayout.setObjectName("addCharSet_Hlayout")
        self.CharCase_combobox = QtWidgets.QComboBox(self.PassGen_Page)
        self.CharCase_combobox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CharCase_combobox.sizePolicy().hasHeightForWidth())
        self.CharCase_combobox.setSizePolicy(sizePolicy)
        self.CharCase_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.CharCase_combobox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CharCase_combobox.setFont(font)
        self.CharCase_combobox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CharCase_combobox.setFrame(True)
        self.CharCase_combobox.setObjectName("CharCase_combobox")
        self.CharCase_combobox.addItem("")
        self.CharCase_combobox.addItem("")
        self.CharCase_combobox.addItem("")
        self.addCharSet_Hlayout.addWidget(self.CharCase_combobox)
        self.CharCase_combobox.setVisible(False)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.addCharSet_Hlayout.addItem(spacerItem2)
        self.charSet_VLayout.addLayout(self.addCharSet_Hlayout)
        self.PassGen_formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.charSet_VLayout)
        self.ExcChar_label = QtWidgets.QLabel(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ExcChar_label.setFont(font)
        self.ExcChar_label.setObjectName("ExcChar_label")
        self.PassGen_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ExcChar_label)
        self.ExcChar_lEdit = QtWidgets.QLineEdit(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ExcChar_lEdit.setFont(font)
        self.ExcChar_lEdit.setInputMask("")
        self.ExcChar_lEdit.setObjectName("ExcChar_lEdit")
        self.PassGen_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ExcChar_lEdit)
        self.PassType_label = QtWidgets.QLabel(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PassType_label.setFont(font)
        self.PassType_label.setObjectName("PassType_label")
        self.PassGen_formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.PassType_label)
        self.passType_HLayout = QtWidgets.QHBoxLayout()
        self.passType_HLayout.setObjectName("passType_HLayout")
        self.ProPassType_radiobtn = QtWidgets.QRadioButton(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ProPassType_radiobtn.setFont(font)
        self.ProPassType_radiobtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ProPassType_radiobtn.setObjectName("ProPassType_radiobtn")
        self.PassType_radiobtnGroup = QtWidgets.QButtonGroup(MainWindow)
        self.PassType_radiobtnGroup.setObjectName("PassType_radiobtnGroup")
        self.PassType_radiobtnGroup.addButton(self.ProPassType_radiobtn)
        self.passType_HLayout.addWidget(self.ProPassType_radiobtn)
        self.RandomPassType_randombtn = QtWidgets.QRadioButton(self.PassGen_Page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RandomPassType_randombtn.setFont(font)
        self.RandomPassType_randombtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RandomPassType_randombtn.setObjectName("RandomPassType_randombtn")
        self.PassType_radiobtnGroup.addButton(self.RandomPassType_randombtn)
        self.passType_HLayout.addWidget(self.RandomPassType_randombtn)
        self.PassGen_formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.passType_HLayout)
        self.verticalLayout_4.addLayout(self.PassGen_formLayout)
        self.AdvPassOpt_frame = QtWidgets.QFrame(self.PassGen_Page)
        self.AdvPassOpt_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.AdvPassOpt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AdvPassOpt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AdvPassOpt_frame.setLineWidth(1)
        self.AdvPassOpt_frame.setObjectName("AdvPassOpt_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.AdvPassOpt_frame)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.NAPassSug_checkbox = QtWidgets.QCheckBox(self.AdvPassOpt_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NAPassSug_checkbox.setFont(font)
        self.NAPassSug_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NAPassSug_checkbox.setObjectName("NAPassSug_checkbox")
        self.verticalLayout_3.addWidget(self.NAPassSug_checkbox)
        self.verticalLayout_4.addWidget(self.AdvPassOpt_frame)
        self.AdvPassOpt_frame.setVisible(False)
        self.GenPassBtn_HLayout = QtWidgets.QHBoxLayout()
        self.GenPassBtn_HLayout.setObjectName("GenPassBtn_HLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.GenPassBtn_HLayout.addItem(spacerItem3)
        self.GenPass_btn = QtWidgets.QPushButton(self.PassGen_Page)
        self.GenPass_btn.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GenPass_btn.setFont(font)
        self.GenPass_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GenPass_btn.setStyleSheet("background-color: rgb(188, 188, 188);")
        self.GenPass_btn.setObjectName("GenPass_btn")
        self.GenPassBtn_HLayout.addWidget(self.GenPass_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.GenPassBtn_HLayout.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.GenPassBtn_HLayout)
        self.ShowGenPass_Hlayout = QtWidgets.QHBoxLayout()
        self.ShowGenPass_Hlayout.setObjectName("ShowGenPass_Hlayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ShowGenPass_Hlayout.addItem(spacerItem5)
        self.ShowGenPass_label = QtWidgets.QLabel(self.PassGen_Page)
        self.ShowGenPass_label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShowGenPass_label.setFont(font)
        self.ShowGenPass_label.setText("")
        self.ShowGenPass_label.setObjectName("ShowGenPass_label")
        self.ShowGenPass_Hlayout.addWidget(self.ShowGenPass_label)
        self.ShowGenPassPut_label = QtWidgets.QLabel(self.PassGen_Page)
        self.ShowGenPassPut_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ShowGenPassPut_label.setFont(font)
        self.ShowGenPassPut_label.setText("")
        self.ShowGenPassPut_label.setObjectName("ShowGenPassPut_label")
        self.ShowGenPassPut_label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ShowGenPass_Hlayout.addWidget(self.ShowGenPassPut_label)
        self.ShowGenPassPut_label.setTextInteractionFlags(Qt.TextSelectableByMouse | Qt.TextSelectableByKeyboard)
        self.ShowGenPassPut_label.setOpenExternalLinks(True)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ShowGenPass_Hlayout.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.ShowGenPass_Hlayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.PassGen_Page)
        self.Login_Page = QtWidgets.QWidget()
        self.Login_Page.setObjectName("Login_Page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Login_Page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.Login_vFrame = QtWidgets.QFrame(self.Login_Page)
        self.Login_vFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.Login_vFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Login_vFrame.setObjectName("Login_vFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Login_vFrame)
        self.verticalLayout_2.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoginPage_label = QtWidgets.QLabel(self.Login_vFrame)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.LoginPage_label.setFont(font)
        self.LoginPage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.LoginPage_label.setObjectName("LoginPage_label")
        self.verticalLayout_2.addWidget(self.LoginPage_label)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.Login_FormLayout = QtWidgets.QFormLayout()
        self.Login_FormLayout.setContentsMargins(20, 0, 50, 20)
        self.Login_FormLayout.setHorizontalSpacing(20)
        self.Login_FormLayout.setVerticalSpacing(40)
        self.Login_FormLayout.setObjectName("Login_FormLayout")
        self.LoginPass_label = QtWidgets.QLabel(self.Login_vFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LoginPass_label.setFont(font)
        self.LoginPass_label.setObjectName("LoginPass_label")
        self.Login_FormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LoginPass_label)
        self.LoginPass_lEdit = QtWidgets.QLineEdit(self.Login_vFrame)
        self.LoginPass_lEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LoginPass_lEdit.setFont(font)
        self.LoginPass_lEdit.setObjectName("LoginPass_lEdit")
        self.Login_FormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LoginPass_lEdit)
        self.LoginUsernm_label = QtWidgets.QLabel(self.Login_vFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LoginUsernm_label.setFont(font)
        self.LoginUsernm_label.setObjectName("LoginUsernm_label")
        self.Login_FormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LoginUsernm_label)
        self.LoginUsernm_lEdit = QtWidgets.QLineEdit(self.Login_vFrame)
        self.LoginUsernm_lEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LoginUsernm_lEdit.setFont(font)
        self.LoginUsernm_lEdit.setObjectName("LoginUsernm_lEdit")
        self.Login_FormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LoginUsernm_lEdit)
        self.verticalLayout_2.addLayout(self.Login_FormLayout)
        self.LoginBtn_HLayout = QtWidgets.QHBoxLayout()
        self.LoginBtn_HLayout.setContentsMargins(-1, 20, -1, -1)
        self.LoginBtn_HLayout.setSpacing(10)
        self.LoginBtn_HLayout.setObjectName("LoginBtn_HLayout")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LoginBtn_HLayout.addItem(spacerItem11)
        self.LoginBtn_Vlayout = QtWidgets.QVBoxLayout()
        self.LoginBtn_Vlayout.setSpacing(10)
        self.LoginBtn_Vlayout.setObjectName("LoginBtn_Vlayout")
        self.Login_PBtn_2 = QtWidgets.QPushButton(self.Login_vFrame)
        self.Login_PBtn_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Login_PBtn_2.setFont(font)
        self.Login_PBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login_PBtn_2.setStyleSheet("background-color: rgb(188, 188, 188);")
        self.Login_PBtn_2.setFlat(False)
        self.Login_PBtn_2.setObjectName("Login_PBtn_2")
        self.LoginBtn_Vlayout.addWidget(self.Login_PBtn_2)
        self.SignUpLink_Pbtn = QtWidgets.QPushButton(self.Login_vFrame)
        self.SignUpLink_Pbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignUpLink_Pbtn.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 162, 162, 80), stop:1 rgba(255, 201, 201, 0));\n"
                                           "color: rgb(0, 0, 255);")
        self.SignUpLink_Pbtn.setFlat(True)
        self.SignUpLink_Pbtn.setObjectName("SignUpLink_Pbtn")
        self.LoginBtn_Vlayout.addWidget(self.SignUpLink_Pbtn)
        self.LoginBtn_HLayout.addLayout(self.LoginBtn_Vlayout)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LoginBtn_HLayout.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.LoginBtn_HLayout)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.horizontalLayout_3.addWidget(self.Login_vFrame)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.stackedWidget.addWidget(self.Login_Page)
        self.SignUp_Page = QtWidgets.QWidget()
        self.SignUp_Page.setObjectName("SignUp_Page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.SignUp_Page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SignUp_label = QtWidgets.QLabel(self.SignUp_Page)
        self.SignUp_label.setMinimumSize(QtCore.QSize(0, 0))
        self.SignUp_label.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.SignUp_label.setFont(font)
        self.SignUp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SignUp_label.setObjectName("SignUp_label")
        self.verticalLayout_5.addWidget(self.SignUp_label)
        self.SignUpPage_Hlayout = QtWidgets.QHBoxLayout()
        self.SignUpPage_Hlayout.setObjectName("SignUpPage_Hlayout")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SignUpPage_Hlayout.addItem(spacerItem16)
        self.frame = QtWidgets.QFrame(self.SignUp_Page)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.SignUpForm_Vlayout = QtWidgets.QVBoxLayout(self.frame)
        self.SignUpForm_Vlayout.setSpacing(20)
        self.SignUpForm_Vlayout.setObjectName("SignUpForm_Vlayout")
        self.SignUpFill_Formlayout = QtWidgets.QFormLayout()
        self.SignUpFill_Formlayout.setContentsMargins(0, 50, -1, 20)
        self.SignUpFill_Formlayout.setHorizontalSpacing(20)
        self.SignUpFill_Formlayout.setVerticalSpacing(40)
        self.SignUpFill_Formlayout.setObjectName("SignUpFill_Formlayout")
        self.FirNm_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FirNm_label.setFont(font)
        self.FirNm_label.setObjectName("FirNm_label")
        self.SignUpFill_Formlayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.FirNm_label)
        self.FirNm_lEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FirNm_lEdit.setFont(font)
        self.FirNm_lEdit.setObjectName("FirNm_lEdit")
        self.SignUpFill_Formlayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.FirNm_lEdit)
        self.MiddleNm_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MiddleNm_label.setFont(font)
        self.MiddleNm_label.setObjectName("MiddleNm_label")
        self.SignUpFill_Formlayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.MiddleNm_label)
        self.MiddleNm_lEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MiddleNm_lEdit.setFont(font)
        self.MiddleNm_lEdit.setObjectName("MiddleNm_lEdit")
        self.SignUpFill_Formlayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.MiddleNm_lEdit)
        self.Surnm_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Surnm_label.setFont(font)
        self.Surnm_label.setObjectName("Surnm_label")
        self.SignUpFill_Formlayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Surnm_label)
        self.Surnm_lEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Surnm_lEdit.setFont(font)
        self.Surnm_lEdit.setObjectName("Surnm_lEdit")
        self.SignUpFill_Formlayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Surnm_lEdit)
        self.DOB_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DOB_label.setFont(font)
        self.DOB_label.setObjectName("DOB_label")
        self.SignUpFill_Formlayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.DOB_label)
        self.DOB_dEdit = QtWidgets.QDateEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DOB_dEdit.setFont(font)
        self.DOB_dEdit.setObjectName("DOB_dEdit")
        self.SignUpFill_Formlayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.DOB_dEdit)
        self.initial_date = self.DOB_dEdit.date()
        self.MobNo_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MobNo_label.setFont(font)
        self.MobNo_label.setObjectName("MobNo_label")
        self.SignUpFill_Formlayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.MobNo_label)
        self.MobNo_lEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MobNo_lEdit.setFont(font)
        self.MobNo_lEdit.setObjectName("MobNo_lEdit")
        self.SignUpFill_Formlayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.MobNo_lEdit)
        self.SignUpPass_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SignUpPass_label.setFont(font)
        self.SignUpPass_label.setObjectName("SignUpPass_label")
        self.SignUpFill_Formlayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.SignUpPass_label)
        self.SignUpPass_lEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SignUpPass_lEdit.setFont(font)
        self.SignUpPass_lEdit.setObjectName("SignUpPass_lEdit")
        self.SignUpFill_Formlayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.SignUpPass_lEdit)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SignUpFill_Formlayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.SignUpFill_Formlayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.SignUpForm_Vlayout.addLayout(self.SignUpFill_Formlayout)
        self.SignUpBtn_hlayout = QtWidgets.QHBoxLayout()
        self.SignUpBtn_hlayout.setObjectName("SignUpBtn_hlayout")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SignUpBtn_hlayout.addItem(spacerItem17)
        self.SignUp_PBtn = QtWidgets.QPushButton(self.frame)
        self.SignUp_PBtn.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SignUp_PBtn.setFont(font)
        self.SignUp_PBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignUp_PBtn.setStyleSheet("background-color: rgb(188, 188, 188);")
        self.SignUp_PBtn.setObjectName("SignUp_PBtn")
        self.SignUpBtn_hlayout.addWidget(self.SignUp_PBtn)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SignUpBtn_hlayout.addItem(spacerItem18)
        self.SignUpForm_Vlayout.addLayout(self.SignUpBtn_hlayout)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SignUpForm_Vlayout.addItem(spacerItem19)
        self.SignUpPage_Hlayout.addWidget(self.frame)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SignUpPage_Hlayout.addItem(spacerItem20)
        self.verticalLayout_5.addLayout(self.SignUpPage_Hlayout)
        self.stackedWidget.addWidget(self.SignUp_Page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.SimPass_PBtn, self.AdvPass_PBtn)
        MainWindow.setTabOrder(self.AdvPass_PBtn, self.Login_PBtn)
        MainWindow.setTabOrder(self.Login_PBtn, self.PassLength_SEdit)
        MainWindow.setTabOrder(self.PassLength_SEdit, self.CharCase_combobox)
        MainWindow.setTabOrder(self.CharCase_combobox, self.AlphaSet_checkbox)
        MainWindow.setTabOrder(self.AlphaSet_checkbox, self.NumSet_checkbox)
        MainWindow.setTabOrder(self.NumSet_checkbox, self.SpeCharSet_checkbox)

        self.warning_box = QMessageBox()
        self.warning_box.setIcon(QMessageBox.Warning)
        self.warning_box.setWindowTitle("Warning")
        self.msg_box = QMessageBox()
        self.msg_box.setWindowTitle("Success")
        self.msg_box.setIcon(QMessageBox.Information)

        ################################### Backend Function #################################################################
        ### Login
        self.Login_PBtn.clicked.connect(self.showLogin_outPage)
        self.Login_PBtn_2.clicked.connect(self.loginFunction)

        ### Sign Up
        self.SignUpLink_Pbtn.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.SignUp_PBtn.clicked.connect(self.SignUpFunction)

        ### Generate Password
        self.SimPass_PBtn.clicked.connect(lambda checked, show_frame=False: self.showPage(show_frame))
        self.AdvPass_PBtn.clicked.connect(lambda checked, show_frame=True: self.showPage(show_frame))

        self.GenPass_btn.clicked.connect(self.GenPass_Function)
        self.AlphaSet_checkbox.stateChanged.connect(self.checkbox_state_changed)

    def checkbox_state_changed(self,state):
        if state == 2:
            self.CharCase_combobox.setVisible(True)
        else:
            self.CharCase_combobox.setVisible(False)

    def showPage(self, show_frame):
        self.AdvPassOpt_frame.setVisible(show_frame)
        self.AdvPage = show_frame

    def showLogin_outPage(self):
        if self.Login_PBtn.text() == 'Login':
            self.stackedWidget.setCurrentWidget(self.Login_Page)
        else:
            self.Login_PBtn.setText('Login')
            self.UserNm_label.setText(" ")
            self.currUser = None

    def check_user_existence(self, username, password):
        url = f"{self.firebase_config['databaseURL']}/Users/{username}.json"
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            if data is not None:
                url = f"{self.firebase_config['databaseURL']}/Users/{username}/Login_Password.json"
                response = requests.get(url)
                if response.status_code == 200:
                    data1 = response.json()
                    if data1 == password:
                        return True
        return False

    def loginFunction(self):
        login_usernm = self.LoginUsernm_lEdit.text()
        login_pass = self.LoginPass_lEdit.text()
        if login_usernm:
            if login_pass:
                if self.check_user_existence(login_usernm, login_pass):
                    self.msg_box.setText("You are successfully logged in .")
                    self.msg_box.exec_()
                    self.stackedWidget.setCurrentIndex(0)
                    self.UserNm_label.setText("Hello " + login_usernm)
                    self.Login_PBtn.setText("Logout")
                    self.currUser = login_usernm
                    self.LoginUsernm_lEdit.clear()
                    self.LoginPass_lEdit.clear()
                else:
                    self.warning_box.setText(" Please enter the correct Username/Password !!")
                    self.warning_box.setStandardButtons(QMessageBox.Ok)
                    self.warning_box.exec_()
            else:
                self.warning_box.setText(" Please enter the password !!")
                self.warning_box.setStandardButtons(QMessageBox.Ok)
                self.warning_box.exec_()
        else:
            self.warning_box.setText(" Please enter the Username !!")
            self.warning_box.setStandardButtons(QMessageBox.Ok)
            self.warning_box.exec_()

    def checking_empty_fields(self):
        line_edits = [self.lineEdit, self.FirNm_lEdit, self.MiddleNm_lEdit, self.Surnm_lEdit, self.SignUpPass_lEdit]
        count=0
        for line_edit in line_edits:
            if line_edit.text().strip() == "":
                line_edit.setStyleSheet("border: 2px solid red;")
            else:
                line_edit.setStyleSheet("")
                count = count+1
        selected_date = self.DOB_dEdit.date()
        if selected_date != self.initial_date:
            count = count+1
            self.DOB_dEdit.setStyleSheet("")
        else:
            self.DOB_dEdit.setStyleSheet("border: 2px solid red;")
        phone_number = self.MobNo_lEdit.text().strip()
        regex = r"^\d{10}$"
        if re.match(regex, phone_number):
            count = count +1
            self.MobNo_lEdit.setStyleSheet("")
        else:
            self.MobNo_lEdit.setStyleSheet("border: 2px solid red;")
        if count == 7:
            return True
        else:
            return False

    def SignUpFunction(self):
        if self.checking_empty_fields():
            data = {"DOB": self.DOB_dEdit.text(), "Login_Password": self.SignUpPass_lEdit.text(), "MobileNo" : self.MobNo_lEdit.text(), "Name": self.FirNm_lEdit.text() +' '+ self.MiddleNm_lEdit.text() +' '+ self.Surnm_lEdit.text()}
            user_ref = self.root_ref.child("Users").child(self.lineEdit.text())
            user_ref.set(data)
            self.msg_box.setText("You are successfully registered.")
            self.msg_box.exec_()
            self.stackedWidget.setCurrentIndex(1)
        else:
            pass

    def generate_random_password(self,charset, length):
        if not charset:
            return ''
        password = ''.join(random.choice(charset) for _ in range(length))
        return password

    def generate_alternate_password(self,charset1, charset2, length):
        password = ""
        if not ( charset1 and charset2):
            return password
        for i in range(length):
            if i % 2 == 0:
                password += random.choice(charset1)
            else:
                password += random.choice(charset2)
        return password

    def GenPass_Function(self):
        charset = ''
        if self.AlphaSet_checkbox.isChecked():
            if self.CharCase_combobox.currentIndex() == 0:
                charset = string.ascii_uppercase
            elif self.CharCase_combobox.currentIndex() == 1:
                charset = string.ascii_lowercase
            else:
                charset = string.ascii_letters
        if self.NumSet_checkbox.isChecked():
            charset = charset + string.digits
        if self.SpeCharSet_checkbox.isChecked():
            charset = charset + '!@#$'
        if (self.AlphaSet_checkbox.isChecked() or self.NumSet_checkbox.isChecked() or self.SpeCharSet_checkbox.isChecked()) != True :
            self.warning_box.setText(" Please choose the character set")
            self.warning_box.setStandardButtons(QMessageBox.Ok)
            self.warning_box.exec_()
            return
        excl_char = self.ExcChar_lEdit.text().strip()
        excl_char = ''.join(char for char in excl_char if char not in string.punctuation + ' ')
        final_charset = ''.join(char for char in charset if char not in excl_char)
        if self.RandomPassType_randombtn.isChecked():
            length = int(self.PassLength_SEdit.text())
            random_password = self.generate_random_password(final_charset, length)
        elif self.ProPassType_radiobtn.isChecked():
            length = int(self.PassLength_SEdit.text())
            final_charset1 = ''.join(char for char in final_charset if char not in '!@#$' + string.digits + 'aeiouAEIOU')
            final_charset2 = ''.join(char for char in final_charset if char in 'aeiouAEIOU')
            final_charset3 = ''.join(char for char in final_charset if char in '!@#$' + string.digits )
            if not (self.NumSet_checkbox.isChecked() & self.SpeCharSet_checkbox.isChecked()):
                random_password = self.generate_alternate_password(final_charset1,final_charset2,length)
            elif not self.AlphaSet_checkbox.isChecked():
                self.warning_box.setText(" Please choose Alphabet character set first ")
                self.warning_box.setStandardButtons(QMessageBox.Ok)
                self.warning_box.exec_()
                return
            else:
                pron_password = self.generate_alternate_password(final_charset1, final_charset2, round(length* 0.7) )
                random_password = pron_password + self.generate_random_password(final_charset3, length - round(length*0.7))

        else :
            self.warning_box.setText(" Please choose the Password Type")
            self.warning_box.setStandardButtons(QMessageBox.Ok)
            self.warning_box.exec_()
            return
        if self.AdvPage:
            if self.NAPassSug_checkbox.isChecked():
                if self.currUser == None:
                    self.warning_box.setText(" Please Log in")
                    self.warning_box.setStandardButtons(QMessageBox.Ok)
                    self.warning_box.exec_()
                    return
                else:
                    data_path = f"Users/{self.currUser}/PasswordGen"
                    data = self.root_ref.child(data_path).get()
                    pre_password_list = list(data.values()) if data else []
                    if random_password in pre_password_list:
                        self.GenPass_Function()
                    else:
                        user_ref = self.root_ref.child("Users").child(f"{self.currUser}/PasswordGen")
                        key = 'Password_' + str(len(pre_password_list) +2)
                        data = {key : random_password}
                        user_ref.update(data)
        self.ShowGenPass_label.setText(' Generated Password is : ')
        self.ShowGenPassPut_label.setText(random_password)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random Password Generator"))
        self.AppName_label.setText(_translate("MainWindow", "Random Password Generator"))
        self.SimPass_PBtn.setText(_translate("MainWindow", "Generate Password"))
        self.AdvPass_PBtn.setText(_translate("MainWindow", "Store Password"))
        self.Login_PBtn.setText(_translate("MainWindow", "Login"))
        self.PassLen_label.setText(_translate("MainWindow", "length"))
        self.CharSet_label.setText(_translate("MainWindow", "Character Set"))
        self.AlphaSet_checkbox.setText(_translate("MainWindow", "Alphabets"))
        self.NumSet_checkbox.setText(_translate("MainWindow", "Numbers"))
        self.SpeCharSet_checkbox.setText(_translate("MainWindow", "Special Character"))
        self.CharCase_combobox.setItemText(0, _translate("MainWindow", "UPPERCASE"))
        self.CharCase_combobox.setItemText(1, _translate("MainWindow", "lowercase"))
        self.CharCase_combobox.setItemText(2, _translate("MainWindow", "Both"))
        self.ExcChar_label.setText(_translate("MainWindow", "Exclude Character"))
        self.ExcChar_lEdit.setPlaceholderText(_translate("MainWindow", "Enter characters to exclude Enter characters to exclude without space"))
        self.PassType_label.setText(_translate("MainWindow", "Password Type"))
        self.ProPassType_radiobtn.setText(_translate("MainWindow", "Pronounceable"))
        self.RandomPassType_randombtn.setText(_translate("MainWindow", "Random"))
        self.NAPassSug_checkbox.setText(_translate("MainWindow", "Avoid previous password suggesions"))
        self.GenPass_btn.setText(_translate("MainWindow", "Generate Password"))
        self.LoginPage_label.setText(_translate("MainWindow", "Login"))
        self.LoginPass_label.setText(_translate("MainWindow", "Password"))
        self.LoginUsernm_label.setText(_translate("MainWindow", "Username"))
        self.Login_PBtn_2.setText(_translate("MainWindow", "Login"))
        self.SignUpLink_Pbtn.setText(_translate("MainWindow", "Don\'t have account ? Sign up here"))
        self.SignUp_label.setText(_translate("MainWindow", "Sign Up"))
        self.FirNm_label.setText(_translate("MainWindow", "First Name"))
        self.MiddleNm_label.setText(_translate("MainWindow", "Middle Name"))
        self.Surnm_label.setText(_translate("MainWindow", "Surname"))
        self.DOB_label.setText(_translate("MainWindow", "Date Of Birth"))
        self.MobNo_label.setText(_translate("MainWindow", "Mobile No."))
        self.SignUpPass_label.setText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.SignUp_PBtn.setText(_translate("MainWindow", "Sign Up"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())